theme = "hugo-theme-docs"
themesdir = "../.."


baseURL = "/"
canonifyURLs = true

languageCode = "ru-ru"
DefaultContentLanguage = "ru"

title = "ProjectName | CompanyName"

[params]
projectName = "My Project"
projectLogoUrl = "https://rwstatic.ru/h/meta/avatar.png"
materialDesignTheme = "deep_purple-blue" # default is 'blue_grey-pink'

noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
ordersectionsby = "weight"


[outputs]
home = [ "HTML", "RSS", "JSON"]

